"
This is a ""null"" editor file, created when a save or open dialog is cancelled.

"
Class {
	#name : 'MDEditorNoFile',
	#superclass : 'MDEditorFile',
	#category : 'MicroEd',
	#package : 'MicroEd'
}

{ #category : 'accessing' }
MDEditorNoFile >> basename [
	^ self shouldBeImplemented
]

{ #category : 'accessing' }
MDEditorNoFile >> fullName [
	^ self shouldBeImplemented
]

{ #category : 'testing' }
MDEditorNoFile >> isNew [
	^ self shouldBeImplemented
]
